version: '3.3'

services:

  #### INFRASTRUCTURE ####
  activemq:
    image: webcenter/activemq:latest
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
    environment:
      ACTIVEMQ_NAME: amq
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'True'
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    volumes:
      - /container_data/activemq/data:/data/activemq
      - /container_data/activemq/log:/var/log/activemq

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db



  #### PLATFORM SERVICES ####

  eresearch-scidir-consumer:
    image: chriniko/eresearch-scidir-consumer:1.0
    depends_on:
      - activemq
    ports:
      - 8080:8080

  eresearch-scopus-consumer:
    image: chriniko/eresearch-scopus-consumer:1.0
    depends_on:
      - activemq
    ports:
      - 8082:8082

  eresearch-dblp-consumer:
    image: chriniko/eresearch-dblp-consumer:1.0
    depends_on:
      - activemq
    ports:
      - 8884:8884

  eresearch-author-finder:
    image: chriniko/eresearch-author-finder:1.0
    depends_on:
      - activemq
    ports:
      - 8083:8083

  eresearch-author-matcher:
    image: chriniko/eresearch-author-matcher:1.0
    ports:
      - 8881:8881


volumes:
  data-volume:
  my-db:
