package com.eresearch.repositorer.dto.authormatcher.response;

public enum StringMetricAlgorithm {

    SIMON_WHITE,
    JARO,
    JARO_WINKLER,
    COSINE_SIMILARITY,
    EUCLIDEAN_DISTANCE,
    BLOCK_DISTANCE,
    DAMERAU_LEVENSHTEIN,
    DICE,
    GENERALIZED_JACCARD,
    IDENTITY,
    JACCARD,
    LONGEST_COMMON_SUBSEQUENCE,
    LONGEST_COMMON_SUBSTRING,
    MONGE_ELKAN,
    NEEDLEMAN_WUNCH,
    OVERLAP_COEFFICIENT,
    Q_GRAMS_DISTANCE,
    SMITH_WATERMAN,
    SMITH_WATERMAN_GOTOH,
    LEVENSHTEIN

}
